# Generated by Django 4.0.4 on 2022-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_dislikes_alter_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
