# Generated by Django 4.0.4 on 2022-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comments_created_comments_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
