# Generated by Django 4.0.4 on 2022-04-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='userName',
            new_name='user_name',
        ),
    ]
